model: empty_model
per_year_outputs_path: "/mnt/c/Users/jebediahc/OneDrive/鱼丸车仔/TUM-before-arrival/Project\ Earth\ Observation\ Data\ Analysis/Project-files-Soil-Moisture/per_year_outputs/"
date: "2020-01-15"

raw_path: "please_specify_raw_path"
processed_path: "data/processed"

log_path: "logs/logger_training.log"

demo_path: "data/demo"
demo_nc_path: "data/demo/2020-1.nc"
demo_datetime: "2020-01-01T12:00:00"

# == train config ==

months:
  - "2020-1"
  - "2020-2"
  - "2020-3"
  - "2020-4"
  - "2020-5"
  - "2020-6"
  - "2020-7"


run_name: "test-untiled"

raw_folder: "data/raw"
intermediate_folder: "data/processed"
use_channels:
  - "swvl1"
  - "ro"
  - "e"
  - "tp"
input_days: 20
predict_days: 10
batch_size: 0
epochs: 100