model: empty_model
model_type: "3dcnn_lstm_lite"  # 可选: "convlstm", "3dcnn_lstm", "3dcnn_lstm_lite", "3dcnn_lstm_micro"
per_year_outputs_path: ""
date: "2020-01-15"

raw_path: "please_specify_raw_path"
processed_path: "data/processed"

log_path: "logs/logger_training.log"

demo_path: "data/demo"
demo_nc_path: "data/demo/2020-1.nc"
demo_datetime: "2020-01-01T12:00:00"

# == train config ==

months:
  - "2020-1"
  - "2020-2"
  - "2020-3"
  - "2020-4"


run_name: "test-untiled"

raw_folder: "data/raw"
intermediate_folder: "data/processed"
use_channels:
  - "swvl1"
  - "ro"
  - "e"
  - "tp"
input_days: 20
predict_days: 10
batch_size: 2
epochs: 10